/*CARA KONEKSI MYSQL VIA TERMINAL*/
cd xampp\mysql\bin;
>Mysql -u root -p;

/*CARA MENAMPILKAN DATABSE
>SHOW DATABASES;

/*CARA MEMBUAT DATABASE*/
CREATE DATABASE '11rpl1_db';

/*CARA MEMBUAT TABLE*/
CREATE TABLE 'siswa'(

id_siswa INT(11) PRIMARY KEY AUTO INCREMENT,
nis CHAR(10),
nama_lengkap VARCHAR(255),
jk CHAR(1),
tmp_lahir VARCHAR(255),
tgl_lahir DATE,
alamat TEXT,
no_hp CHAR,
tanggal_entri DATETIME,

/*CARA MENAMPILKAN TABLE*/
SHOW TABLES;

/*CARA MENAMPILKAN SPESIFIKASI TABLE*/
DESCRIBE 'siswa';

/*CARA MENAMBAHKAN RECORD KE TABLE*/
id_siswa = NULL,
nis = '10801050'
nama_lengkap = ihsan fajar ramadhan'
jk = 'L',
tmp_lahir = 'SUBANG',
tgl_lahir = '2002-11-27',
alamat = 'DUSUN PATROL',
no_hp = '089xxx'
tanggal_entri = NOW();

/*CARA MEAMPILKAN SELURUH DATA TABLE*/
SELECT*FROM 'siswa';

/*CARA MENAMPILKAN DATA DENGAN KONDISI TERTENTU*/
SELECT*FROM 'siswa' WHERE jk = 'P';

/*CARA MENAMPILKAN BEBERAPA/BATAS RECORD PADA TABLE*/
SELECT*FROM 'siswa' LIMIT 3, 5;

/*CARA MENAMPILKAN/MENGURUTKAN RECORD BERDASARKAN FIELD TERTENTU*/
SELECT*FROM 'siswa' ORDER BY tgl_lahir DESC;

/*CARA MENAMPILKAN FIELD MENGGUNAKAN FUNCTION*/
SELECT UPPER(alamat) FROM 'siswa';

/* CARA MENAMPILKAN BEBERAPA FIELD DENGAN KONDISI TERTENTU*/
SELECT nama_lengkap, tmp_lahir, tgl_lahir, FROM 'siswa' WHERE YEAR(tgl_lahir) = '2002';

/* CARA MEMPERBAHARUI DATA PADA TABEL */
UPDATE 'siswa' SET tmp_lahir = 'BANDUNG', tgl_lahir = '2003-01-01' WHERE id_siswa = '1';

/* CARA MENGHAPUS DATA/RECORD */
DELETE*FROM 'siswa' WHERE id_siswa '1';